# RXID Drug Search Service

service: rxid-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  timeout: 10
  region: us-east-1
  apiGateway:
    apiKeySourceType: HEADER

functions:
  getRxIdentifier:
    handler: handler.getDrugIdentifiers
    events:
        - http:
            path: drug/search/getRxIdentifier
            method: get
            cors: true
            private: true
  getRxInfo:
    handler: handler.getDrugInfo
    events:
        - http:
            path: drug/search/getRxInfo
            method: get
            cors: true
            private: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

custom:
  webpackIncludeModules: true
  # Prune Old Deployments, otherwise you'll max out on storage space
  prune:
    automatic: true
    number: 3
